spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /api/authenticate/**
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path= /api/account/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /api/authenticate/user/**
server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: mySecretKey
  expireMs: 1200
  refrEshexpireMs: 1200
